[package]
name = "mcdaemon-rust"
version = "0.1.0"
authors = ["Sciroccogti <scirocco_gti@yeah.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ctrlc = "3.1.4"
colored = "1.9.3"
